// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SbsaB-zFrPfPLiARvEHqh9EFwd5PPAE',
    appId: '1:867846081661:web:a0692fd6b01513a1b4f514',
    messagingSenderId: '867846081661',
    projectId: 'the-sss-store',
    authDomain: 'the-sss-store.firebaseapp.com',
    storageBucket: 'the-sss-store.appspot.com',
    measurementId: 'G-B39VHQ310W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCbuPiZX9zL4Ra7zs_lJeIsoRX3NrU9g',
    appId: '1:867846081661:android:095b9300df932b10b4f514',
    messagingSenderId: '867846081661',
    projectId: 'the-sss-store',
    storageBucket: 'the-sss-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_wIo2VDK1-ZbMg56j1FTG6ATCBhuYcM',
    appId: '1:867846081661:ios:fec240973272b3c3b4f514',
    messagingSenderId: '867846081661',
    projectId: 'the-sss-store',
    storageBucket: 'the-sss-store.appspot.com',
    iosClientId:
        '867846081661-v744l09spqteh8sj5o217juv467pr7i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.the3sStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_wIo2VDK1-ZbMg56j1FTG6ATCBhuYcM',
    appId: '1:867846081661:ios:fec240973272b3c3b4f514',
    messagingSenderId: '867846081661',
    projectId: 'the-sss-store',
    storageBucket: 'the-sss-store.appspot.com',
    iosClientId:
        '867846081661-v744l09spqteh8sj5o217juv467pr7i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.the3sStore',
  );
}
